# Number of days of inactivity before an issue becomes stale
daysUntilStale: 365
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - 'Priority: Major'
  - 'Priority: Critical'
  - 'Priority: Minor'
  - Information
# Label to use when marking an issue as stale
staleLabel: 'Status: Abandoned'
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Hey there, it looks like there has been no activity on this issue recently. 
  Has the issue been fixed, or does it still require attention? 
  This issue may be closed if no further activity occurs. Thank you for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
