disabled_rules:
  - line_length
  - function_body_length
  - identifier_name
  - trailing_comma
type_body_length: 500
file_length: 500
cyclomatic_complexity:
  ignores_case_statements: true
opening_brace:
  allow_multiline_func: true
