name: Discussion
description: I want to discuss something that is related to this project
labels: ["Other"]
assignees: []
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Before opening the issue, have you...?
      description: This is to help us minimize the amount of duplicate issues, which allows us more time for actual development.
      options:
        - label: Searched for existing issues
          required: true
  - type: textarea
    id: discussion
    validations:
      required: true
    attributes:
      label: Discussion
      description: Feel free to type anything you want to discuss related to the project. Do note that we have a seperate template for questions.
