name: Monitor Issue
description: MonitorControl is not working as expected on my monitor.
labels: ["Monitor Issue"]
assignees: []
body:
  - type: checkboxes
    attributes:
      label: Before opening the issue, have you...?
      description: This is to help us minimize the amount of duplicate issues, which allows us more time for actual development.
      options:
        - label: Searched for existing issues
          required: true
        - label: Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
          required: true
        - label: Updated MonitorControl to the latest version (if applicable)
          required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the issue
      description: A clear and concise description of the problem.
      placeholder: Volume & Brightness controls are not working on my LG 38GN950.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    validations:
      required: false
    attributes:
      label: Anything else?
      description: |
        Screenshots? Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: textarea
    validations:
      required: false
    attributes:
      label: Environment Information (please complete the following information)
      description: |
        examples:
            - **macOS version**: 11.4 Big Sur
            - **Mac model**: MacBook Pro (16-inch, 2019)
            - **MonitorControl version**: v2.1.0
            - **Monitor(s)**: LG 38GN950, LG 27UN83A
            - **Monitor Cable(s)/Connection(s)**:  
            &nbsp;&nbsp;- Mac Mini -> DisplayPort 2.1 -> LG 38GN950
            &nbsp;&nbsp;- Mac Mini -> Belkin Thunderbolt 3 Dock Core -> LG 27UN83A
            - **Apple Silicon/M1 (yes or no)**: no
      value: |
        - macOS version:
        - Mac model:
        - MonitorControl version:
        - Monitor(s):
        - Monitor Cable(s)/Connection(s):
        - Apple Silicon/M1 (yes or no):
      render: markdown
