name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: brew bundle
        run: brew bundle

      - name: xcodebuild
        run: xcodebuild build -project MonitorControl.xcodeproj -arch "x86_64"  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -scheme "MonitorControl"
